### ISSUE TITLE
Error when running land cover degradation with local data

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#129]
An error has occurred while executing Python code: 

TypeError: in method 'BuildVRTInternalNames', argument 3 of type 'GDALBuildVRTOptions *' 
Traceback (most recent call last):
  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\calculate_lc.py", line 169, in btn_calculate
    self.calculate_locally()
  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\calculate_lc.py", line 248, in calculate_locally
    lc_initial_vrt = self.lc_setup_tab.use_custom_initial.get_vrt()
  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\data_io.py", line 1097, in get_vrt
    bandList=[self.get_bandnumber()])
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdal.py", line 1221, in BuildVRT
    return BuildVRTInternalNames(destName, srcDSNamesTab, opts, callback, callback_data)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdal.py", line 3147, in BuildVRTInternalNames
    return _gdal.BuildVRTInternalNames(*args)
TypeError: in method 'BuildVRTInternalNames', argument 3 of type 'GDALBuildVRTOptions *'

**Comment by azvoleff** [comment]
Fixed.
