### ISSUE TITLE
Costa Rica error when using local shapefile

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#143]
It is in a custom coordinate system but QGIS seems to recognize you. The file can be downloaded from here:

https://www.dropbox.com/s/1upyvqfq2dx5gk8/CostaRica.zip?dl=0

TrendsEarth error:

2018-04-09T20:37:44	0	Setting up AOI from file at D:/Documents and Settings/mgonzalez-roglich/Desktop/CostaRica/Limite_CR.shp"
2018-04-09T20:37:44	0	Transforming layer from "+proj=tmerc +lat_0=0 +lon_0=-84 +k=0.9999 +x_0=500000 +y_0=0 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs" to "+proj=longlat +datum=WGS84 +no_defs". Wrap is False.
2018-04-09T20:37:44	0	Transforming layer from "+proj=longlat +datum=WGS84 +no_defs" to "+proj=longlat +datum=WGS84 +no_defs". Wrap is False.

Python error:

2018-04-09T20:37:46	1	Traceback (most recent call last):
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\calculate_sdg.py", line 162, in btn_calculate
			    crosses_180th, geojsons = self.aoi.bounding_box_gee_geojson()
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\calculate.py", line 261, in bounding_box_gee_geojson
			    return self.meridian_split()
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\calculate.py", line 179, in meridian_split
			    e_intersection = hemi_e.Intersection(union)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\ogr.py", line 6351, in Intersection
			    return _ogr.Geometry_Intersection(self, *args)
			ValueError: Received a NULL pointer.

**Comment by azvoleff** [comment]
@gdaldegan You wouldn't happen to still have this file, would you?

**Comment by gdaldegan** [comment]
@azvoleff I believe you meant to ask @mgroglich

**Comment by azvoleff** [comment]
Whoops, sorry. Yes- @mgroglich

**Comment by azvoleff** [comment]
@mgroglich - can you confirm if this is still an issue? If you don't have the file, just close this one until we can reproduce it.

**Comment by azvoleff** [comment]
@mgroglich - this still an issue?
