### ISSUE TITLE
Error running SDG 11.3.1 on some shapefiles

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#196]
I separated the shapefiles Lahouari shared with us into individual files (one per city). For 20 of them the tool submits the task correctly, but for 5 it gives the following errors:

File that works:
https://www.dropbox.com/s/h7wnsi3nii575kz/works.zip?dl=0

File which gives the error:
https://www.dropbox.com/s/rpjs6bpvduvs8xj/doesnotwork.zip?dl=0

Python errors:
2019-01-29T14:49:41	1	Traceback (most recent call last):
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\calculate_urban.py", line 150, in btn_calculate
			    self.calculate_on_GEE()
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\calculate_urban.py", line 168, in calculate_on_GEE
			    crosses_180th, geojsons = self.aoi.bounding_box_gee_geojson()
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\calculate.py", line 312, in bounding_box_gee_geojson
			    return self.meridian_split()
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\calculate.py", line 194, in meridian_split
			    raise
			TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

Trends.Earth Error:

2019-01-29T14:49:41	0	Setting up AOI from file at D:/dropbox/ci/00_trendsearth/sdg11_3_1/country_verification/usa/25LargestUrbanAreas/unique/Phoenix.shp"
2019-01-29T14:49:41	0	Transforming layer from "+proj=longlat +datum=WGS84 +no_defs" to "+proj=longlat +datum=WGS84 +no_defs". Wrap is False. Datatype is polygon.
2019-01-29T14:49:41	0	Merging features
2019-01-29T14:49:41	0	Transforming layer from "+proj=longlat +datum=WGS84 +no_defs" to "+proj=longlat +datum=WGS84 +no_defs". Wrap is False. Datatype is polygon.
2019-01-29T14:49:41	0	Invalid feature with attributes: [u'Phoenix--Mesa, AZ', 10L, u'Phoenix'].

**Comment by azvoleff** [comment]
That is typically an issue with the geometry. I'll look into this, but probably won't be until the week after next - that too late? Even if the geometry does have an issue, I need to set it up so the tool gives a more useful error message.

**Comment by gdaldegan** [comment]
Mariano to look for the data stored in Dropbox links
