### ISSUE TITLE
Coordinates issue from rollbar

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#282]
Project: | trends.earth-API
-- | --
Environment: | prod
Code Version: | unspecified
Host: | c0ac5826e548
Timestamp: | 2020-05-14   07:47

A new item has occurred for the first time. View full details of the item at: https://rollbar.com/azvoleff/trends.earth-API/items/32/. 
View the occurrence that triggered this notification at: https://rollbar.com/azvoleff/trends.earth-API/items/32/occurrences/123373405148/

Message
KeyError: Uncaught exception
Traceback
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import gefcore
  File "/project/gefcore/__init__.py", line 47, in <module>
    run(params)
  File "/project/gefcore/runner.py", line 69, in run
    raise error
  File "/project/gefcore/runner.py", line 64, in run
    result = main.run(params, logger)
  File "/project/gefcore/script/main.py", line 187, in run
    aoi = ee.Geometry.MultiPolygon(get_coords(geojson))
  File "/opt/conda/envs/env/lib/python3.8/site-packages/ee/geometry.py", line 469, in MultiPolygon
    return Geometry(Geometry._parseArgs('MultiPolygon', 4, all_args))
  File "/opt/conda/envs/env/lib/python3.8/site-packages/ee/geometry.py", line 651, in _parseArgs
    if (Geometry._hasServerValue(result['coordinates']) or
KeyError: 'coordinates'

**Comment by azvoleff** [comment]
Closing as no longer visible in rollbar.
