### ISSUE TITLE
Rollbar coordinates error

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#283]
May be related to #282.

Project: | trends.earth-API
-- | --
Environment: | prod
Code Version: | unspecified
Host: | 058148ff7c8b
Timestamp: | 2020-05-09   10:25

A new item has occurred for the first time. View full details of the item at: https://rollbar.com/azvoleff/trends.earth-API/items/30/. 
View the occurrence that triggered this notification at: https://rollbar.com/azvoleff/trends.earth-API/items/30/occurrences/122913754157/

Message
EEException: Uncaught exception

Traceback
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import gefcore
  File "/project/gefcore/__init__.py", line 47, in <module>
    run(params)
  File "/project/gefcore/runner.py", line 69, in run
    raise error
  File "/project/gefcore/runner.py", line 64, in run
    result = main.run(params, logger)
  File "/project/gefcore/script/main.py", line 66, in run
    perf = productivity_performance(prod_perf_year_initial,
  File "/opt/conda/envs/env/lib/python3.8/site-packages/landdegradation/productivity.py", line 220, in productivity_performance
    poly = ee.Geometry(geojson, opt_geodesic=False)
  File "/opt/conda/envs/env/lib/python3.8/site-packages/ee/computedobject.py", line 32, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/opt/conda/envs/env/lib/python3.8/site-packages/ee/geometry.py", line 146, in __init__
    self._computed_equivalent = apifunction.ApiFunction.lookup(
  File "/opt/conda/envs/env/lib/python3.8/site-packages/ee/function.py", line 80, in apply
    result = computedobject.ComputedObject(self, self.promoteArgs(named_args))
  File "/opt/conda/envs/env/lib/python3.8/site-packages/ee/function.py", line 116, in promoteArgs
    raise ee_exception.EEException(
EEException: Unrecognized arguments {'geodesic'} to function: Constructs a new Point from the given x,y coordinates.

Args:
  coordinates: The coordinates of this Point in x,y order.
  crs: The coordinate reference system of the coordinates. The
      default is the projection of the inputs, where Numbers are
      assumed to be EPSG:4326.

**Comment by azvoleff** [comment]
@gdaldegan - can you look into this?

**Comment by gdaldegan** [comment]
sure! I should've done it already, my bad!

**Comment by gdaldegan** [comment]
Alex,
the tool is throwing that error when the user sets the coordinate point directly in the x and y fields or imports a coordinate point through the option 'Area from file' when calculating **SDG 15.3.1** or its sub-indicators. I've been replicating the error. 
Related to this function https://developers.google.com/earth-engine/api_docs#ee.algorithms.geometryconstructors.point
**SDG 11** seems to be running fine either setting the coordinate point directly or importing the shape.
