### ISSUE TITLE
Python error installing plugin in new release QGIS v 3.14.15 Trends.Earth plugin 1.0.2

### ISSUE THREAD

**Issue by MLNoon** [ConservationInternational/trends.earth#312]
QGIS v 3.14.15 Trends.Earth plugin 1.0.2 (note: I have downloaded and installed these same versions and they are working fine on my computer. User noted that he deleted the LDMP folder).

ImportError: PyQt4 classes cannot be imported in QGIS 3.x. Use PyQt5 or the version independent qgis.PyQt import instead. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\__init__.py", line 49, in classFactory
    from LDMP.plugin import LDMPPlugin
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\plugin.py", line 30, in 
    from LDMP.about import DlgAbout
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\about.py", line 27, in 
    resource_suffix='')
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\PyQt5\uic\__init__.py", line 201, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 59, in 
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2mapillary\resources.py", line 10, in 
    from PyQt4 import QtCore
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 741, in _import
    raise ImportError(msg)
ImportError: PyQt4 classes cannot be imported in QGIS 3.x.
Use PyQt5 or the version independent qgis.PyQt import instead.

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.14.15-Pi Pi, d5114d2cfa 
Ruta de Python:
•	C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
•	C:\Users\DELL\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
•	C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python
•	C:\Users\DELL\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
•	C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\Scripts
•	C:\Program Files\QGIS 3.14\bin\python37.zip
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\DLLs
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib
•	C:\Program Files\QGIS 3.14\bin
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\Pythonwin
•	C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2mapillary
•	C:\Users\DELL\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2mapillary\extlibs
•	C:\Users\DELL\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
•	C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isochrones
•	C:\Users\DELL\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
•	C:\Users\DELL\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\isochrones\iso\utilities
•	C:\Users\DELL\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

**Comment by azvoleff** [comment]
Thanks Monica! This isn’t coming from Trends.Earth. It looks like it coming from another plugin they have installed called “go2mapillary” – so they should reach out to the authors of that plugin (it looks like that plugin is using PyQt4, which isn't supported by QGIS3).
