### ISSUE TITLE
error installing plugin on 3.10.6 and 3.14

### ISSUE THREAD

**Issue by MLNoon** [ConservationInternational/trends.earth#315]
I am new to trends.earth and want to explore more, but I failed to open the plugin after successful installation. It said " Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method. I copied the entire message below. I tried it on QGIS 3.10.6 and QGIS 3.14, both showed the same responses. 
Looking forward to some help. 
Thank you.

Adi Mahardika
PS:
The message:
Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method 

TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "D:/Documents and Settings/imahardika/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\__init__.py", line 49, in classFactory
    from LDMP.plugin import LDMPPlugin
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Documents and Settings/imahardika/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\plugin.py", line 30, in 
    from LDMP.about import DlgAbout
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Documents and Settings/imahardika/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\about.py", line 27, in 
    resource_suffix='')
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\PyQt5\uic\__init__.py", line 201, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 59, in 
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Documents and Settings/imahardika/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources.py", line 1251, in 
    qInitResources()
  File "D:/Documents and Settings/imahardika/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources.py", line 1243, in qInitResources
    qt_resource_name, qt_resource_data)
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.0-Pi Pi, 9f7028fd23 
Python Path:
•	C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python
•	D:\Documents and Settings\imahardika\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
•	D:\Documents and Settings\imahardika\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
•	D:/Documents and Settings/imahardika/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	D:/Documents and Settings/imahardika/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\Scripts
•	C:\Program Files\QGIS 3.14\bin\python37.zip
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\DLLs
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib
•	C:\Program Files\QGIS 3.14\bin
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\Pythonwin
•	D:/Documents and Settings/imahardika/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	D:/Documents and Settings/imahardika/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
•	D:\Documents and Settings\imahardika\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by azvoleff** [comment]
This one doesn't look like it is coming from us - looks like it is from another plugin "qgis2web". @MLNoon - can you ask them to reach out with the same report to the developers of that plugin?
