### ISSUE TITLE
Error for downloading Land Data for Malawi

### ISSUE THREAD

**Issue by Ishimotojuri** [ConservationInternational/trends.earth#502]
I would like to download the land cover data (ESA CCI Land Cover) and Land productivity data for Malawi, but the error message popped out: KeyError: 'year_start'

             
2021-08-21T22:56:34     WARNING    Traceback (most recent call last):
              File "C:\Users/ishim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\jobs.py", line 331, in btn_download
              download_cloud_results(job, f, self.tr)
              File "C:\Users/ishim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\jobs.py", line 455, in download_cloud_results
              add_layer(out_file, band_number, band_info)
              File "C:\Users/ishim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\layers.py", line 356, in add_layer
              title = get_band_title(band_info)
              File "C:\Users/ishim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\layers.py", line 496, in get_band_title
              return tr_style_text(style['title']).format(**band_info['metadata'])
             KeyError: 'year_start'

**Comment by azvoleff** [comment]
What version of the plugin are you? This I think is a bug in a past version.

**Comment by chinwuchen** [comment]
I encountered the same KeyError: 'year_start' in a similar situation. The error occurred when I tried to "load data" from a previously downloaded file (also from ESA CCI Land Cover).

The plugin version is 1.0.8, apparently the most recent stable one.

My system is MacOS Big Sur (11.6.1), Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)]  QGIS version: 3.16.15-Hannover Hannover, e7fdad6431  

<img width="1220" alt="Screen Shot 2022-01-03 at 10 07 48 PM" src="https://user-images.githubusercontent.com/62773146/148016842-589afca8-85d5-4786-bdc3-5301f2a24617.png">

**Comment by Jay-Qu** [comment]
I have the issue on MacOS Big Sur (11.6.2) when trying to load a previously downloaded "Trends.Earth" dataset into QGIS.
Any help is much appreciated :)

Python version: 3.9.4 (v3.9.4:1f2e3088f3, Apr  4 2021, 12:32:44) [Clang 6.0 (clang-600.0.57)] 
QGIS version: 3.18.3-Zürich Zürich, exported

**Here is the Error Message:**

An error has occurred while executing Python code: 

KeyError: 'year_start' 
Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/data_io.py", line 507, in browse_file
    res = self.update_layer_list(f)
  File "/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/data_io.py", line 515, in update_layer_list
    self.layer_list = get_layer_info_from_file(os.path.normcase(os.path.normpath(f)))
  File "/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/data_io.py", line 1223, in get_layer_info_from_file
    layers_filtered.append((data_file, get_band_title(band_info), n + 1, band_info))
  File "/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/layers.py", line 496, in get_band_title
    return tr_style_text(style['title']).format(**band_info['metadata'])
KeyError: 'year_start'

**Comment by sebjwallace** [comment]
@[azvoleff](https://github.com/azvoleff) do you know if a fix is already in for this? Else I can create a PR.
