### ISSUE TITLE
Can't install on mac

### ISSUE THREAD

**Issue by Jes-Lop** [ConservationInternational/trends.earth#503]
I get this error when try to install on macOS 10.15.7, QGIS 3.18.3

`Failed to load 'LDMP' add-on due to an error calling its classFactory() method 
KeyError: 'Can only index numba types with slices with no start or stop, got 4.' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 49, in classFactory
    from LDMP.plugin import LDMPPlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 24, in 
    from LDMP.download_data import DlgDownload
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/download_data.py", line 30, in 
    from LDMP.calculate import DlgCalculateBase, get_script_slug
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 59, in 
    from LDMP.calculate_numba import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate_numba.py", line 130, in 
    @cc.export('ldn_total_deg', 'f4[4](i2[:,:], b1[:,:], f4[:,:])')
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/pycc/cc.py", line 136, in export
    fn_args, fn_retty = sigutils.normalize_signature(sig)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/sigutils.py", line 24, in normalize_signature
    parsed = _parse_signature_string(sig)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/sigutils.py", line 14, in _parse_signature_string
    return eval(signature_str, {}, types.__dict__)
  File "", line 1, in 
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/types/abstract.py", line 185, in __getitem__
    ndim, layout = self._determine_array_spec(args)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/types/abstract.py", line 210, in _determine_array_spec
    raise KeyError(f"Can only index numba types with slices with no start or stop, got {args}.")
KeyError: 'Can only index numba types with slices with no start or stop, got 4.'

Versión de Python: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
Versión de QGIS: 3.18.3-Zürich Zürich, 735cc85be9 

Ruta de Python:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kmltools/libs
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/forms
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
.
D:\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/forms`

**Comment by azvoleff** [comment]
Not valid on latest version
