### ISSUE TITLE
Trends.Earth plug in not loadable in QGIS

### ISSUE THREAD

**Issue by grunewac** [ConservationInternational/trends.earth#520]
![image](https://user-images.githubusercontent.com/97929554/149863647-8070b60d-9a26-43da-b2c6-738cde7112b5.png)

I just installed QGIS-LTR on my Mac (macOS Catalina 10.15.7), and am receiving an error message when trying to install the trends.earth plugin. The message states: 
"Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method 
RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. If using conda try: #> conda install clang_osx-64 clangxx_osx-64"

Any suggestions?

**Comment by azvoleff** [comment]
Thanks, this comes up in the code that tries to use numba to compile some of the functions used in generating summary tables within QGIS. If you don't have a compiler then the compilation will fail, but it should do so more nicely (just printing a log message, not giving a python error). What version of the plugin are you on? And can you paste the full python error you see?

**Comment by grunewac** [comment]
Hello - I have QGIS LTR 3.16 installed. 

The full error message is below: 

Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method 

KeyError: 'Can only index numba types with slices with no start or stop, got 4.' 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 49, in classFactory
    from LDMP.plugin import LDMPPlugin
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 24, in 
    from LDMP.download_data import DlgDownload
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/download_data.py", line 30, in 
    from LDMP.calculate import DlgCalculateBase, get_script_slug
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 59, in 
    from LDMP.calculate_numba import *
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate_numba.py", line 130, in 
    @cc.export('ldn_total_deg', 'f4[4](i2[:,:], b1[:,:], f4[:,:])')
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/pycc/cc.py", line 136, in export
    fn_args, fn_retty = sigutils.normalize_signature(sig)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/sigutils.py", line 24, in normalize_signature
    parsed = _parse_signature_string(sig)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/sigutils.py", line 14, in _parse_signature_string
    return eval(signature_str, {}, types.__dict__)
  File "", line 1, in 
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/types/abstract.py", line 185, in __getitem__
    ndim, layout = self._determine_array_spec(args)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/types/abstract.py", line 210, in _determine_array_spec
    raise KeyError(f"Can only index numba types with slices with no start or stop, got {args}.")
KeyError: 'Can only index numba types with slices with no start or stop, got 4.'


Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.16.15-Hannover Hannover, e7fdad6431 

Python Path:
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8
/Users/clairegrunewald/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by azvoleff** [comment]
This is an error related to numba. The error message says you are missing a compiler it needs. Are you running python from Anaconda? If so suggest running the command it indicates:

`conda install clang_osx-64 clangxx_osx-64`

That would let you use just-in-time compilation through numba (which will let summaries, etc., generate faster in Trends.Earth). Either way though we need to add something to catch that error and give a cleaner error message.

**Comment by azvoleff** [comment]
Closing as stale. Reopen if still an issue
