### ISSUE TITLE
Error on Downloading Algorithm Results

### ISSUE THREAD

**Issue by gkahiu** [ConservationInternational/trends.earth#521]
Am encountering the error below when downloading results from the cloud:

Traceback (most recent call last):
  File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\main_widget.py", line 266, in refresh_after_cache_update
    maybe_download_finished_results()
  File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\main_widget.py", line 600, in maybe_download_finished_results
    job_manager.download_available_results()
  File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\jobs\manager.py", line 426, in download_available_results
    self.download_job_results(job)
  File "AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\jobs\manager.py", line 387, in download_job_results
    output_path = handler(job)
  File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\jobs\manager.py", line 619, in _download_cloud_results
    combine_all_bands_into_vrt(main_raster_file_paths, vrt_file)
  File "\src\trends.earth\LDMP\ext-libs\te_algorithms\gdal\util.py", line 112, in combine_all_bands_into_vrt
    this_gt = in_ds.GetGeoTransform()
AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'

Am running [faa981a](https://github.com/ConservationInternational/trends.earth/commit/faa981a104f5d3ef5141d9251618d6e91e26084a) in the _develop_ branch.

**Comment by azvoleff** [comment]
@gkahiu - what plugin version are you on? Mostly wondering if you still see this on latest develop (as this should be fixed).

**Comment by gkahiu** [comment]
Thanks. I can confirm the issue is fixed in the latest _develop_
