### ISSUE TITLE
getting an error when trying to delete a data listed under the Dataset tab

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#558]

**Comment by cjvandiemen** [comment]
When I try to delete a dataset with ID `201bde94-4d87-444e-8c55-0f256e8df0d9` I get the following error: 

```
An error has occurred while executing Python code: 

AttributeError: 'LocalResults' object has no attribute 'uri' 
Traceback (most recent call last):
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/utils.py", line 79, in delete_dataset
    manager.job_manager.delete_job(job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 369, in delete_job
    _delete_job_datasets(job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 1080, in _delete_job_datasets
    if (job.results.uri and not is_gdal_vsi_path(job.results.uri.uri)):
AttributeError: 'LocalResults' object has no attribute 'uri'


Python version: 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0] 
QGIS version: 3.24.1-Tisler Tisler, 5709b82461 

Python Path:
/usr/share/qgis/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/home/chris/trends_earth_binaries_1-99-8_3-24
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
```

**Comment by cjvandiemen** [comment]
When I try to delete dataset ID `2db4cc18-d14c-4977-b7aa-e7b104b34240` user: [chris.vandiemen@opengeohub.org](mailto:chris.vandiemen@opengeohub.org) I get the following error:

```
An error has occurred while executing Python code: 

AttributeError: 'RasterResults' object has no attribute 'data_path' 
Traceback (most recent call last):
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/utils.py", line 78, in delete_dataset
    remove_layer_from_qgis(job.results.data_path)
AttributeError: 'RasterResults' object has no attribute 'data_path'


Python version: 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0] 
QGIS version: 3.24.1-Tisler Tisler, 5709b82461 

Python Path:
/usr/share/qgis/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/home/chris/trends_earth_binaries_1-99-8_3-24
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
```

**Comment by azvoleff** [comment]
Fixed
