### ISSUE TITLE
T.E does not (re)start

### ISSUE THREAD

**Issue by cjvandiemen** [ConservationInternational/trends.earth#598]
When I click the trends.earth icon in QGIS it switches 'off' when I click it again to turn it on again I get the following error: 

```
An error has occurred while executing Python code: 

AttributeError: 'JsonResults' object has no attribute 'rasters' 
Traceback (most recent call last):
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 211, in run_docked_interface
    self.dock_widget = main_widget.MainWidget(
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 189, in __init__
    self.update_local_state()  # perform an initial update, before the scheduler kicks in
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 379, in update_local_state
    job_manager.refresh_local_state()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 265, in refresh_local_state
    self._refresh_local_downloaded_jobs()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 826, in _refresh_local_downloaded_jobs
    for j in self._get_local_jobs(jobs.JobStatus.DOWNLOADED)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 883, in _get_local_jobs
    job = _load_raw_job(raw_job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 100, in _load_raw_job
    _set_results_extents(job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 77, in _set_results_extents
    for raster in job.results.rasters.values():
AttributeError: 'JsonResults' object has no attribute 'rasters'


Python version: 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0] 
QGIS version: 3.24.1-Tisler Tisler, 5709b82461 

Python Path:
/usr/share/qgis/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/home/chris/trends_earth_binaries_1-99-8_3-24
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
```

Using T.E version [1.99.8](https://plugins.qgis.org/plugins/LDMP/version/1.99.8/) updated at ma feb. 21 12:45:17 2022. 

software | version
-- | --
QGIS version | 3.24.1-Tisler
QGIS code revision | 5709b82461
Qt version | 5.15.2
Python version | 3.9.7
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.35.5
PDAL version | 2.2.0
PostgreSQL client version | 13.6 (Ubuntu 13.6-0ubuntu0.21.10.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 21.10

**Comment by cjvandiemen** [comment]
I tried restarting and reinstalling the plugin also deleting the local data but the same error is coming up

**Comment by azvoleff** [comment]
Thanks Chris. Do you still see this with the latest zipfile? (just note the latest zipfile has some partial fixes in it right now related to the false positive/negative tool, so while you'll see that new tool in there, it isn't yet fully functional)

**Comment by cjvandiemen** [comment]
I tried reinstalling the T.E plugin using [the zip file](https://s3.amazonaws.com/trends.earth/sharing/LDMP_QGIS3.zip) from the repository. I get the following error:

```
An error has occurred while executing Python code: 

AttributeError: 'FileResults' object has no attribute 'rasters' 
Traceback (most recent call last):
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 303, in run_docked_interface
    self.dock_widget = main_widget.MainWidget(
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 197, in __init__
    self.update_local_state()  # perform an initial update, before the scheduler kicks in
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 421, in update_local_state
    job_manager.refresh_local_state()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 238, in refresh_local_state
    self._refresh_local_downloaded_jobs()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 850, in _refresh_local_downloaded_jobs
    for j in self._get_local_jobs(jobs.JobStatus.DOWNLOADED)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 913, in _get_local_jobs
    job = _load_raw_job(raw_job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 93, in _load_raw_job
    _set_results_extents(job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 70, in _set_results_extents
    for raster in job.results.rasters.values():
AttributeError: 'FileResults' object has no attribute 'rasters'


Python version: 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0] 
QGIS version: 3.24.1-Tisler Tisler, 5709b82461 

Python Path:
/usr/share/qgis/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/home/chris/trends_earth_binaries_1-99-9_3-24
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/chris/.local/lib/python3.9/site-packages
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
```

**Comment by cjvandiemen** [comment]
I reinstalled the plugin from the zip file now I removed all the data that was on my drive. I now got the following message:

```
An error has occurred while executing Python code: 

AttributeError: 'FileResults' object has no attribute 'get_all_uris' 
Traceback (most recent call last):
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 305, in refresh_after_cache_update
    maybe_download_finished_results()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 656, in maybe_download_finished_results
    job_manager.download_available_results()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 518, in download_available_results
    self.download_job_results(job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 490, in download_job_results
    metadata.init_dataset_metadata(job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/metadata.py", line 83, in init_dataset_metadata
    for u in job.results.get_all_uris():
AttributeError: 'FileResults' object has no attribute 'get_all_uris'


Python version: 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0] 
QGIS version: 3.24.1-Tisler Tisler, 5709b82461 

Python Path:
/usr/share/qgis/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/home/chris/trends_earth_binaries_1-99-9_3-24
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/chris/.local/lib/python3.9/site-packages
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
```

**Comment by azvoleff** [comment]
I'm still not 100% sure this is the issue, but 4a06af041b487742bbeafcb543880fe82247c3a5 may address it. Can you try again with the latest zipfile (just pushed another new one).

**Comment by azvoleff** [comment]
Moved to #606
