### ISSUE TITLE
Error when downloading data generated using older T.E version while using T.E version 1.99.9

### ISSUE THREAD

**Issue by cjvandiemen** [ConservationInternational/trends.earth#606]
I am using the same account for testing different versions of T.E. I get the following error when I try to download data from an older version while using version 1.99.9

```
old results)

An error has occurred while executing Python code: 

marshmallow.exceptions.ValidationError: {'results': [ValidationError({'rasters': ['Missing data for required field.'], 'type': ['Must be equal to ResultType.RASTER_RESULTS.'], 'urls': ['Unknown field.'], 'bands': ['Unknown field.']}), ValidationError({'type': ['Must be equal to ResultType.FILE_RESULTS.']}), ValidationError({'type': ['Must be equal to ResultType.JSON_RESULTS.'], 'data': ['Missing data for required field.']}), ValidationError({'type': ['Must be equal to ResultType.TIME_SERIES_TABLE.'], 'table': ['Missing data for required field.']}), ValidationError({'vector': ['Missing data for required field.'], 'type': ['Must be equal to ResultType.VECTOR_RESULTS.'], 'urls': ['Unknown field.'], 'bands': ['Unknown field.']}), ValidationError({'type': ['Must be equal to ResultType.EMPTY_RESULTS.']})]} 
Traceback (most recent call last):
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 385, in perform_single_update
    self.update_from_remote_state()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 410, in update_from_remote_state
    job_manager.refresh_from_remote_state()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 352, in refresh_from_remote_state
    remote_jobs = get_remote_jobs(end_date=relevant_date)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 1200, in get_remote_jobs
    job = Job.Schema().load(raw_job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/marshmallow_dataclass/__init__.py", line 639, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/marshmallow/schema.py", line 717, in load
    return self._do_load(
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/marshmallow/schema.py", line 900, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'results': [ValidationError({'rasters': ['Missing data for required field.'], 'type': ['Must be equal to ResultType.RASTER_RESULTS.'], 'urls': ['Unknown field.'], 'bands': ['Unknown field.']}), ValidationError({'type': ['Must be equal to ResultType.FILE_RESULTS.']}), ValidationError({'type': ['Must be equal to ResultType.JSON_RESULTS.'], 'data': ['Missing data for required field.']}), ValidationError({'type': ['Must be equal to ResultType.TIME_SERIES_TABLE.'], 'table': ['Missing data for required field.']}), ValidationError({'vector': ['Missing data for required field.'], 'type': ['Must be equal to ResultType.VECTOR_RESULTS.'], 'urls': ['Unknown field.'], 'bands': ['Unknown field.']}), ValidationError({'type': ['Must be equal to ResultType.EMPTY_RESULTS.']})]}


Python version: 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0] 
QGIS version: 3.24.1-Tisler Tisler, 5709b82461 

Python Path:
/usr/share/qgis/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/home/chris/trends_earth_binaries_1-99-9_3-24
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/chris/.local/lib/python3.9/site-packages
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
```

**Comment by azvoleff** [comment]
@cjvandiemen can you try latest zipfile (just pushed)? It should just silently ignore any older jobs it can't understand with the latest code

**Comment by cjvandiemen** [comment]
I tested the same approach using 1.99.9 revision 4eff1a98 and got the following result:

```
An error has occurred while executing Python code: 

NameError: name '_set_results_extents' is not defined 
Traceback (most recent call last):
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 305, in refresh_after_cache_update
    maybe_download_finished_results()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/main_widget.py", line 656, in maybe_download_finished_results
    job_manager.download_available_results()
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 556, in download_available_results
    self.download_job_results(job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 515, in download_job_results
    output_path = handler(job)
  File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 812, in _download_cloud_results
    _set_results_extents(job)
NameError: name '_set_results_extents' is not defined


Python version: 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0] 
QGIS version: 3.24.1-Tisler Tisler, 5709b82461 

Python Path:
/usr/share/qgis/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/home/chris/trends_earth_binaries_1-99-9_3-24
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/chris/.local/lib/python3.9/site-packages
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/home/chris/.local/share/QGIS/QGIS3/profiles/default/python
```
There are now datasets shown in the `datasets` tab

**Comment by azvoleff** [comment]
Thanks, hadn't noticed that one - now fixed in latest zip

**Comment by azvoleff** [comment]
@cjvandiemen - just let me know when you have a chance to test. If now working for you then I'll close this issue.
