### ISSUE TITLE
python error when trying to run Land Cover Change remotely

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#632]
2022-04-28T14:04:52     WARNING    Traceback (most recent call last):
              File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 180, in rowCount
              return len(self.nesting.child.key_with_nodata())
             AttributeError: 'LCLegend' object has no attribute 'key_with_nodata'
             
2022-04-28T14:04:52     WARNING    Traceback (most recent call last):
              File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\main_widget.py", line 510, in launch_algorithm_execution_dialogue
              dialog=dialog_class(self.iface, algorithm_script.script, parent=self)
              File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\calculate_lc.py", line 59, in __init__
              self.lc_setup_widget = lc_widget_class(parent=self)
              File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 1090, in __init__
              self.aggregation_dialog = DlgCalculateLCSetAggregation(
              File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 349, in __init__
              self.setup_nesting_table(self.nesting)
              File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 517, in setup_nesting_table
              for row in range(0, len(nesting.child.key_with_nodata())):
             AttributeError: 'LCLegend' object has no attribute 'key_with_nodata'

**Comment by azvoleff** [comment]
Hmm. Try again @gdaldegan, I must have not pushed it completely

**Comment by azvoleff** [comment]
Whoops, sorry. I do see this. Will look into it and get back to you
