### ISSUE TITLE
Python error when resampling custom land cover data

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#635]
Both @boc84 and I got the following Python error message when importing a custom land cover dataset and setting Modify resolution (in meters) option:

TypeError: Wrong number or type of arguments for overloaded function 'new_CoordinateTransformation'.   Possible C/C++ prototypes are:     OSRCoordinateTransformationShadow::OSRCoordinateTransformationShadow(OSRSpatialReferenceShadow *,OSRSpatialReferenceShadow *)     OSRCoordinateTransformationShadow::OSRCoordinateTransformationShadow(OSRSpatialReferenceShadow *,OSRSpatialReferenceShadow *,OGRCoordinateTransformationOptions *) 
Traceback (most recent call last):
  File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 611, in done
    self.validate_input(value)
  File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 650, in validate_input
    self.ok_clicked()
  File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 769, in ok_clicked
    remap_ret = self.remap_raster(
  File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\data_io.py", line 1048, in remap_raster
    warp_ret = self.warp_raster(temp_tif)
  File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\data_io.py", line 1099, in warp_raster
    resample_mode = self.get_resample_mode(temp_vrt)
  File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\data_io.py", line 959, in get_resample_mode
    in_res = self.get_in_res_wgs84()
  File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\data_io.py", line 999, in get_in_res_wgs84
    tx = osr.CoordinateTransformation(
  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg\osgeo\osr.py", line 928, in __init__
    _osr.CoordinateTransformation_swiginit(self, _osr.new_CoordinateTransformation(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_CoordinateTransformation'.
  Possible C/C++ prototypes are:
    OSRCoordinateTransformationShadow::OSRCoordinateTransformationShadow(OSRSpatialReferenceShadow *,OSRSpatialReferenceShadow *)
    OSRCoordinateTransformationShadow::OSRCoordinateTransformationShadow(OSRSpatialReferenceShadow *,OSRSpatialReferenceShadow *,OGRCoordinateTransformationOptions *)

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.5-Białowieża Białowieża, c2723178 

Python Path:
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python
C:\Users\gdaldegan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
C:\Users\gdaldegan\trends_earth_binaries_1-99-10_3-22
C:/Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.5\bin\python39.zip
C:\PROGRA~1\QGIS32~1.5\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib
C:\Program Files\QGIS 3.22.5\bin
C:\PROGRA~1\QGIS32~1.5\apps\Python39
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by azvoleff** [comment]
Yep, me too. Will look at it, probably easy fix
