### ISSUE TITLE
Fix import of LC defined in a shapefile

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#636]
Noted in #522 by @gabrieldaldegan:

> just installed the latest exp. version on QGIS 3.22 and got the same message

![te_error](https://user-images.githubusercontent.com/22821787/163244106-14ba804f-c274-4c13-9d55-0dbeae59febe.PNG)

**Comment by azvoleff** [comment]
`TypeError: unsupported operand type(s) for +: 'set' and 'list'
Traceback (most recent call last):
File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 756, in agg_edit
self.load_agg(
File "C:\Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 684, in load_agg
values = values + [child_nodata_code]
TypeError: unsupported operand type(s) for +: 'set' and 'list'




Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
QGIS version: 3.22.5-Białowieża Białowieża, c2723178



Python Path:
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python
C:\Users\gdaldegan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
C:\Users\gdaldegan\trends_earth_binaries_1-99-10_3-22
C:/Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.5\bin\python39.zip
C:\PROGRA~1\QGIS32~1.5\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib
C:\Program Files\QGIS 3.22.5\bin
C:\PROGRA~1\QGIS32~1.5\apps\Python39
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/gdaldegan/AppData/Roaming/QGIS/QGIS3\profiles\default/python`

**Comment by azvoleff** [comment]
@gdaldegan can you send me the shapefile and legend you have been using for testing this?
