### ISSUE TITLE
Couldn't load plugin 'LDMP' due to an error when calling its initGui() method 

### ISSUE THREAD

**Issue by nausea-za** [ConservationInternational/trends.earth#691]
Hi all, relatively new user here. I cannot seem to load the trends.earth plugin in QGIS anymore. Tried reinstalling both QGIS (latest version and stable version), as well as trends.earth plugin but same error. I was using trends.earth v1.0.10 and everything was working fine, when I updated the plugin things started going wrong.

Couldn't load plugin 'LDMP' due to an error when calling its initGui() method

**FileNotFoundError: [WinError 3] The system cannot find the path specified: '/reports/outputs'** 

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/peter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\plugin.py", line 199, in initGui
    self.init_reports()
  File "C:\Users/peter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\plugin.py", line 339, in init_reports
    template_manager.use_data_dir_config_source()
  File "C:\Users/peter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\reports\template_manager.py", line 175, in use_data_dir_config_source
    self.switch_source(ConfigurationSource.DATA_DIR)
  File "C:\Users/peter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\reports\template_manager.py", line 166, in switch_source
    self.create_default_output_dir()
  File "C:\Users/peter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\reports\template_manager.py", line 182, in create_default_output_dir
    os.mkdir(self._default_output_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/reports/outputs'

**Python version**: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
**QGIS version**: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdada 

**Python Path:**

- C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
- C:\Users\peter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
- C:\Users\peter\trends_earth_binaries_2-0_3-26
- C:/Users/peter/AppData/Roaming/QGIS/QGIS3\profiles\default/python
- C:/Users/peter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
- C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
- C:\Program Files\QGIS 3.26.3\bin\python39.zip
- C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
- C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
- C:\Program Files\QGIS 3.26.3\bin
- C:\PROGRA~1\QGIS32~1.3\apps\Python39
- C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
- C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
- C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
- C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
- C:/Users/peter/AppData/Roaming/QGIS/QGIS3\profiles\default/python

Any help would be appreciated.

Thanks

**Comment by azvoleff** [comment]
Fixed by dfae8ba20834709b2f2124a93296b5465a5dd88f
