### ISSUE TITLE
Fix error introduced by dropping exception when buffer is not entered and city is chosen

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#747]
@vermeulendivan [this commit](https://github.com/ConservationInternational/trends.earth/pull/705) leads to issues downstream in the plugin as the changes to [these lines](https://github.com/ConservationInternational/trends.earth/commit/4b6f485d2b51f288e51f12b05d9d6e48ac0bc405#diff-83a68c9253baf538b5700e67e268a543a7cbb9657ed8358ef66855c2858e3291L570-L580) mean a user is no longer warned if they select a city or point but don't choose a buffer. To reproduce, cor example:
- open the land cover tool with "execute locally"
- change the region to a city but don't enter a buffer
- click ok on the settings window

You will then get this error:
```
An error has occurred while executing Python code: 

AttributeError: 'AOI' object has no attribute 'l' 
Traceback (most recent call last):
  File "C:\Users/azvoleff/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\lc_setup.py", line 1407, in populate_combos
    self.initial_year_layer_cb.populate()
  File "C:\Users/azvoleff/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\data_io.py", line 1463, in populate
    aoi = areaofinterest.prepare_area_of_interest()
  File "C:\Users/azvoleff/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\areaofinterest.py", line 582, in prepare_area_of_interest
    is_valid = area_of_interest.isValid()
  File "C:\Users/azvoleff/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\areaofinterest.py", line 396, in isValid
    return self.l.isValid()
AttributeError: 'AOI' object has no attribute 'l'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.26.2-Buenos Aires Buenos Aires, feec3d3b 

Python Path:
C:/OSGeo4W/apps/qgis/./python
C:\Users\azvoleff\Code\LandDegradation\trends.earth\LDMP\ext-libs
C:/Users/azvoleff/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/azvoleff/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/azvoleff/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

The problem is due to the changes on [these lines](https://github.com/ConservationInternational/trends.earth/commit/4b6f485d2b51f288e51f12b05d9d6e48ac0bc405#diff-83a68c9253baf538b5700e67e268a543a7cbb9657ed8358ef66855c2858e3291L570-L580) on that commit. We either can revert and go back to the old behavior of raising an exception that was caught downstream, or else we'll need to modify the code to block saving the settings if a user hasn't chosen a buffer and a point or city was chosen.

**Comment by azvoleff** [comment]
Related to #699
