### ISSUE TITLE
the final SDG indicator, a python error occurred when running locally

### ISSUE THREAD

**Issue by MrShuaiB1** [ConservationInternational/trends.earth#796]
My computer system is Mac os, Qgis is stable version 3.28.14, plug-in is the latest version of internal download. There was no problem in the calculation of sub_indicators, but there was an error in the calculation of SDG15.3.1. I changed a mac computer and it was still the same, which bothered me very much. I hope someone can help me solve it, thank you very much.My English is not very good, please forgive me.
<img width="1109" alt="截屏2024-01-16 13 34 37" src="https://github.com/ConservationInternational/trends.earth/assets/156744888/d6ea2d86-d5a3-436e-ba93-250e0c0ec151">
<img width="355" alt="截屏2024-01-16 13 34 43" src="https://github.com/ConservationInternational/trends.earth/assets/156744888/0ded3a80-a77f-4be5-8ff3-f3791e6d69e1">

**Comment by MrShuaiB1** [comment]
2024-01-16T19:17:25     WARNING    An error occurred while executing Python code：
             
             
             numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
             Use of unsupported opcode (IS_OP) found
             
             File "Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/land_deg/land_deg_numba.py", line 183:
             def calc_lc_trans(lc_bl, lc_tg, multiplier, recode_from=None, recode_to=None):
              
              # raw integer codes to ordinal values prior to calculating transitions
              if recode_from is not None and recode_to is not None:
              ^
             
             
             
             Traceback (most recent call last):
              File "/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 194, in run
              self.results = execution_handler(
              File "/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/localexecution/ldn.py", line 369, in compute_ldn
              return summarise_land_degradation(
              File "/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/land_deg/land_deg.py", line 310, in summarise_land_degradation
              summary_table, output_path, reproj_path = _compute_ld_summary_table(
              File "/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/land_deg/land_deg.py", line 1230, in _compute_ld_summary_table
              ) = _process_region(
              File "/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/land_deg/land_deg.py", line 1174, in _process_region
              summary_table, output_paths = _aoi_process_sequential(inputs)
              File "/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/land_deg/land_deg.py", line 1084, in _aoi_process_sequential
              output = _summarize_tile(item)
              File "/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/land_deg/land_deg.py", line 1038, in _summarize_tile
              result = summarizer.work()
              File "/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/land_deg/worker.py", line 135, in work
              result = self.processing_function(
              File "/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/land_deg/land_deg.py", line 587, in _process_block_summary
              a_lc_trans_lc_deg = calc_lc_trans(
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/dispatcher.py", line 418, in _compile_for_args
              error_rewrite(e, 'unsupported_error')
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/dispatcher.py", line 358, in error_rewrite
              reraise(type(e), e, None)
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/utils.py", line 80, in reraise
              raise value.with_traceback(tb)
             numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
             Use of unsupported opcode (IS_OP) found
             
             File "Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/land_deg/land_deg_numba.py", line 183:
             def calc_lc_trans(lc_bl, lc_tg, multiplier, recode_from=None, recode_to=None):
              
              # raw integer codes to ordinal values prior to calculating transitions
              if recode_from is not None and recode_to is not None:
              ^
             
             
             
             
             
             Python版本： 3.9.5 (default, Sep 10 2021, 16:18:19) 
             [Clang 12.0.5 (clang-1205.0.22.11)]
             
             
             QGIS版本： 3.28.14-Firenze Firenze, b09131c5125
             
             
             Python路径：
             
             /Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/lib-dynload/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python39.zip/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg/Users/zhaojingdong/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by MrShuaiB1** [comment]
I had the same situation on both computers, and I switched between different versions of Qgis, which didn't work. I hope developers can help me, thank you very much. Whether I choose shp file or locale, it's the same result, it doesn't work, but there's no problem when calculating sub_indicators.

**Comment by Winter-Chou** [comment]
你这个问题解决了吗？能联系一下你吗？

**Comment by MrShuaiB1** [comment]
您好，不好意思，我刚看到。这个方法我后面没有在用了，因为不方便。当时我是把Qgis里面的内置的Python里面的用来加速的包给卸载了，然后可以跑，但是速度特别慢。可以参考一下。

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/03/2024 15:07 |
| To | ***@***.***> |
| Cc | MrShuaiB1 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ConservationInternational/trends.earth] the final SDG indicator, a python error occurred when running locally (Issue #796) |

你这个问题解决了吗？能联系一下你吗？

**Comment by Winter-Chou** [comment]
您好，可以加一下您的联系方式吗？想和您咨询些这个插件的相关事情，我看国内做这个的人好像很少。非常感谢🙏

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/26/2024 10:22 |
| To | ***@***.***> |
| Cc | Winter-Chou ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [ConservationInternational/trends.earth] the final SDG indicator, a python error occurred when running locally (Issue #796) |

您好，不好意思，我刚看到。这个方法我后面没有在用了，因为不方便。当时我是把Qgis里面的内置的Python里面的用来加速的包给卸载了，然后可以跑，但是速度特别慢。可以参考一下。

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/03/2024 15:07 |
| To | ***@***.***> |
| Cc | MrShuaiB1 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ConservationInternational/trends.earth] the final SDG indicator, a python error occurred when running locally (Issue #796) |

你这个问题解决了吗？能联系一下你吗？

**Comment by MrShuaiB1** [comment]
可以，您加我vx吧，8234736

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/26/2024 11:36 |
| To | ***@***.***> |
| Cc | MrShuaiB1 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ConservationInternational/trends.earth] the final SDG indicator, a python error occurred when running locally (Issue #796) |

您好，可以加一下您的联系方式吗？想和您咨询些这个插件的相关事情，我看国内做这个的人好像很少。非常感谢🙏

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/26/2024 10:22 |
| To | ***@***.***> |
| Cc | Winter-Chou ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [ConservationInternational/trends.earth] the final SDG indicator, a python error occurred when running locally (Issue #796) |

您好，不好意思，我刚看到。这个方法我后面没有在用了，因为不方便。当时我是把Qgis里面的内置的Python里面的用来加速的包给卸载了，然后可以跑，但是速度特别慢。可以参考一下。

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/03/2024 15:07 |
| To | ***@***.***> |
| Cc | MrShuaiB1 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ConservationInternational/trends.earth] the final SDG indicator, a python error occurred when running locally (Issue #796) |

你这个问题解决了吗？能联系一下你吗？
