### ISSUE TITLE
Couldn't load plugin 'LDMP': problem with typing_extension module

### ISSUE THREAD

**Issue by emcasagrande** [ConservationInternational/trends.earth#812]
Hello, 

I'm trying to load the plugin, but this error appeared (I'm on Windows). I tried reinitializing QGIS settings and installing the most stable version of QGIS (Prizren 3.34.8), but the error still exists: 
**Couldn't load plugin 'LDMP'** 
**TypeError: type 'typing.TypeVar' is not an acceptable base type** 

_Python version_: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
_QGIS version_: 3.34.8-Prizren Prizren, 91642333 

This is the full log >>>

//////////////////////////////////////////////////
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Enrico Casagrande/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\__init__.py", line 117, in 
    from . import conf  # noqa: autoimport
    ^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Enrico Casagrande/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\conf.py", line 10, in 
    from te_schemas.algorithms import ExecutionScript
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Enrico Casagrande\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\te_schemas\algorithms.py", line 6, in 
    import marshmallow_dataclass
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Enrico Casagrande\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\marshmallow_dataclass\__init__.py", line 66, in 
    import typing_inspect
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Enrico Casagrande\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\typing_inspect.py", line 23, in 
    from typing_extensions import _TypedDictMeta as _TypedDictMeta_TE
  File "C:\PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Enrico Casagrande\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\typing_extensions.py", line 1174, in 
    class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type
//////////////////////////////////////////////////
![image](https://github.com/ConservationInternational/trends.earth/assets/91542089/d68cd12c-c553-46d6-ba73-6f3a725af415)

**Comment by emcasagrande** [comment]
Duplicate #806
