### ISSUE TITLE
TypeError: type 'typing.TypeVar' is not an acceptable base type 

### ISSUE THREAD

**Issue by krubjorn** [ConservationInternational/trends.earth#828]
Tried to install Trends.Earth and run into this error

Couldn't load plugin 'LDMP' 

TypeError: type 'typing.TypeVar' is not an acceptable base type 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 404, in loadPlugin
    __import__(packageName)
  File "C:\Users/many3911/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/many3911/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\__init__.py", line 117, in 
    from . import conf  # noqa: autoimport
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users/many3911/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/many3911/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\conf.py", line 10, in 
    from te_schemas.algorithms import ExecutionScript
  File "C:\Users/many3911/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\many3911\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\te_schemas\algorithms.py", line 6, in 
    import marshmallow_dataclass
  File "C:\Users/many3911/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\many3911\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\marshmallow_dataclass\__init__.py", line 66, in 
    import typing_inspect
  File "C:\Users/many3911/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\many3911\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\typing_inspect.py", line 23, in 
    from typing_extensions import _TypedDictMeta as _TypedDictMeta_TE
  File "C:\Users/many3911/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\many3911\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\typing_extensions.py", line 1174, in 
    class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type

Python version: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.38.0-Grenoble Grenoble, 37aa6188bc

**Comment by atomes-epar** [comment]
This appears to be an issue with QGIS python. I was successfully able to load the plugin using QGIS version 3.28

**Comment by azvoleff** [comment]
This is fixed in latest release of Trends.Earth (for all QGIS versions). Use trends.earth 2.1.16 or greater and you should be good to go.
